-- Create purchases table for storing completed transactions
CREATE TABLE IF NOT EXISTS public.purchases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL,
  item_id text NOT NULL,
  transaction_id text NOT NULL,
  status text NOT NULL DEFAULT 'completed',
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  
  CONSTRAINT unique_transaction UNIQUE (transaction_id)
);

-- Create index for faster user lookups
CREATE INDEX IF NOT EXISTS idx_purchases_user_id ON public.purchases (user_id);

-- Add comment explaining the table
COMMENT ON TABLE public.purchases IS 'Stores completed purchases and their status (completed/refunded)';
